# Skills, tools, and domains scanned in job titles + descriptions.
# Longer phrases first. Aliases collapse to the first name.
PHRASES = [
    "distributed systems",
    "machine learning",
    "deep learning",
    "large language models",
    "site reliability",
    "forward deployed",
    "trust and safety",
    "trust & safety",
    "computer vision",
    "natural language processing",
    "data engineering",
    "data science",
    "software engineer",
    "backend engineer",
    "platform engineer",
    "security engineer",
    "research engineer",
    "staff engineer",
    "prompt engineering",
    "github actions",
    "vs code",
    "apache kafka",
    "apache spark",
    "elasticsearch",
    "postgresql",
    "kubernetes",
    "terraform",
    "graphql",
    "typescript",
    "javascript",
    "pytorch",
    "tensorflow",
    "snowflake",
    "databricks",
    "airflow",
    "dbt",
    "kafka",
    "spark",
    "hadoop",
    "redis",
    "mongodb",
    "mysql",
    "oracle",
    "sqlite",
    "python",
    "golang",
    "rust",
    "java",
    "scala",
    "kotlin",
    "swift",
    "ruby",
    "php",
    "c++",
    "c#",
    "go",
    "sql",
    "react",
    "next.js",
    "node.js",
    "nodejs",
    "docker",
    "helm",
    "kind",
    "aws",
    "gcp",
    "azure",
    "linux",
    "git",
    "llm",
    "rag",
    "mlops",
    "cicd",
    "ci/cd",
    "grpc",
    "http",
    "jdbc",
    "tableau",
    "etl",
    "ios",
    "android",
]

ALIASES = {
    "apache kafka": "kafka",
    "apache spark": "spark",
    "nodejs": "node.js",
    "golang": "go",
    "trust & safety": "trust and safety",
    "cicd": "ci/cd",
    "large language models": "llm",
}

SENIORITY = [
    "principal",
    "staff",
    "senior",
    "lead",
    "mid",
    "junior",
    "intern",
]

TITLE_LIKE = {
    "software engineer",
    "backend engineer",
    "platform engineer",
    "security engineer",
    "research engineer",
    "staff engineer",
    "data engineering",
    "data science",
    "forward deployed",
    "site reliability",
}

GENERIC = {
    "http",
    "git",
    "linux",
    "sql",
}
